## 외전 01. JS에서의 비동기처리

---

<br />

### 비동기 처리 
- JS의 비동기 처리란 특정 코드의 연산이 끝날 때까지 코드의 실행을 멈추지 않고 다음 코드를 먼저 실행하는 JS의 특성을 의미

### 비동기 처리 사례

```js
function getData() {
	var tableData;
	$.get('https://domain.com/products/1', function(response) {
		tableData = response;
	});
	return tableData;
}

console.log(getData()); // undefined
```

```js
// #1
console.log('Hello');
// #2
setTimeout(function() {
	console.log('Bye');
}, 3000);
// #3
console.log('Hello Again');

```

- 이처럼 제이쿼리의 ajax와 setTimeout은 비동기적으로 동작한다.

### 콜백함수를 이용한 비동기 처리

```js 
function getData(callbackFunc) {
	$.get('https://domain.com/products/1', function(response) {
		callbackFunc(response); // 서버에서 받은 데이터 response를 callbackFunc() 함수에 넘겨줌
	});
}

getData(function(tableData) {
	console.log(tableData); // $.get()의 response 값이 tableData에 전달됨
});
```

### 콜백 지옥 

```js
$.get('url', function(response) {
	parseValue(response, function(id) {
		auth(id, function(result) {
			display(result, function(text) {
				console.log(text);
			});
		});
	});
});

```
- 이와 같이 작성하면 가독성도 떨어지고 로직을 변경하기 어렵다.

#### 콜백 지옥 해결 방법

```js 
function parseValueDone(id) {
	auth(id, authDone);
}
function authDone(result) {
	display(result, displayDone);
}
function displayDone(text) {
	console.log(text);
}
$.get('url', function(response) {
	parseValue(response, parseValueDone);
});
```

- 위와 같이 각 콜백 함수를 분리해주거나 `Promise`,`Async`를 사용하는 방법이 있다.

---------------------------

### Promise

- `Promise` 는 JS 비동기 처리에 사용되는 객체이다.

```js
// 기존 ajax 통신 코드

function getData(callbackFunc) {
  $.get('url 주소/products/1', function(response) {
    callbackFunc(response); // 서버에서 받은 데이터 response를 callbackFunc() 함수에 넘겨줌
  });
}

getData(function(tableData) {
  console.log(tableData); // $.get()의 response 값이 tableData에 전달됨
});
```

```js
// 위의 ajax 코드에 Promise를 추가한 코드

function getData(callback) {
  // new Promise() 추가
  return new Promise(function(resolve, reject) {
    $.get('url 주소/products/1', function(response) {
      // 데이터를 받으면 resolve() 호출
      resolve(response);
    });
  });
}

// getData()의 실행이 끝나면 호출되는 then()
getData().then(function(tableData) {
  // resolve()의 결과 값이 여기로 전달됨
  console.log(tableData); // $.get()의 reponse 값이 tableData에 전달됨
});
```

### 프로미스의 3가지 상태 
- `Pending(대기)` : 비동기 처리 로직이 아직 완료되지 않은 상태
- `Fulfilled(이행)` : 비동기 처리가 완료되어 프로미스가 결과값을 반환해준 상태
- `Reject(실패)` : 비동기 처리가 실패하거나 오류가 발생한 상태

### 프로미스 체이닝
```js
getData(userInfo)
  .then(parseValue)
  .then(auth)
  .then(diaplay);


var userInfo = {
  id: 'test@abc.com',
  pw: '****'
};

function parseValue() {
  return new Promise({
    // ...
  });
}
function auth() {
  return new Promise({
    // ...
  });
}
function display() {
  return new Promise({
    // ...
  });
}
```

### 프로미스 에러 처리 방법

```js
//then()을 이용한경우
getData().then(
  handleSuccess,
  handleError
);

// catch()를 이용한 경우
getData().then().catch();
```
- `Promise`에서 에러를 처리하는 방법에는 두가지 방식이 있다.
- 위의 코드처럼 `then()`의 두번째인자로 에러처리 콜백함수를 이용하거나
- 그 아래 코드 처럼 `getData().then().catch();` 를 이용하는 방법이 있다.

```js
function getData() {
  return new Promise(function(resolve, reject) {
    reject('failed');
  });
}

// 1. then()의 두 번째 인자로 에러를 처리하는 코드
getData().then(function() {
  // ...
}, function(err) {
  console.log(err);
});

// 2. catch()로 에러를 처리하는 코드
getData().then().catch(function(err) {
  console.log(err);
});
```

##### 프로미스의 에러처리 예제

```js
// then()의 두 번째 인자로는 감지하지 못하는 오류
function getData() {
  return new Promise(function(resolve, reject) {
    resolve('hi');
  });
}

getData().then(function(result) {
  console.log(result);
  throw new Error("Error in then()"); // Uncaught (in promise) Error: Error in then()
}, function(err) {
  console.log('then error : ', err);
});
```
- 위처럼 then()의 첫번째 함수에서 에러가 발생하게 되면 에러를 잡기 어렵다.
- then의 두번째 인자는 getData()로부터 넘어올때 발생하는 에러를 처리하게 된다.

```js
// catch()로 오류를 감지하는 코드
function getData() {
  return new Promise(function(resolve, reject) {
    resolve('hi');
  });
}

getData().then(function(result) {
  console.log(result); // hi
  throw new Error("Error in then()");
}).catch(function(err) {
  console.log('then error : ', err); // then error :  Error: Error in then()
});
```
- 이처럼 catch()를 사용하게 되면 에러를 효과적으로 잡을 수 있다.

-----

### async & await

- `async`와 `await`은 자바스크립트의 비동기 처리 패턴 중 가장 최근에 나온 문법으로 기존의 비동기 처리 방식인 콜백 함수와 프로미스의 단점을 보완하고 개발자가 읽기 좋은 코드를 작성할 수 있게 도와줌

### 

https://joshua1988.github.io/web-development/javascript/js-async-await/

